### ISSUE TITLE
Merging issues back to main branch.

### ISSUE THREAD

**Issue by sdorsher** [thedataincubator/forecaster#15]
We seem to have some problem with merging our issues back to the main branch. I just cloned the repositories and I don't see the update with the locked versions. I know there have been updates. I made one myself involving the bokeh version. I think something is going wrong in our process involving review or pushing back to master. @ZachGlassman could you please clarify how this is supposed to work?

Thanks.

**Comment by ZachGlassman** [comment]
Only instructors can push to master.  You will need to push to a new branch and open a pull request to master.  Once it passes review and tests, either Tim, Dylan, or I will merge into master.  Make sure you push the branch to this repo, you should not need to use a forked repo.

**Comment by sdorsher** [comment]
But my master is my forked repo. Your master is your account. I don't have the password to your account, so I can't push to your master. There must be some way around this.

**Comment by ZachGlassman** [comment]
You will need to push a branch (not master) in this repo and then open a pull request against master.  In principle you can also open a PR from your own master into this master, but we want all the development to happen in this repo.

**Comment by sdorsher** [comment]
I don't have your password. How do I push to this repo first?

**Comment by ZachGlassman** [comment]
You can push a branch to this repo from your account.

**Comment by sdorsher** [comment]
Only instructors can do this. Slack is down and has been for six months. Pull requests were not in general promptly processed. This project was not even central to the class, but rather was something I did as an experiment in github collaboration use. It is an abysmal github collaboration failure. Issue closed.

**Comment by sdorsher** [comment]
Only instructors can do this. Slack is down and has been for six months. Pull requests were not in general promptly processed. This project was not even central to the class, but rather was something I did as an experiment in github collaboration use. It is an abysmal github collaboration failure. Issue closed.
