### ISSUE TITLE
App Purpose

### ISSUE THREAD

**Issue by ZachGlassman** [thedataincubator/forecaster#2]
Please use this issue to discuss and determine a purpose for this application!

**Comment by craw-daddy** [comment]
Not that I am a big fan of football (or soccer, as some call it), but the World Cup is going on right now.  Of course predicting those sorts of outcomes is more difficult than I think we want to take on here.  

Mainly I am spitballing here.  Just trying to start some conversation.

**Comment by ZachGlassman** [comment]
I agree this would be a bit challenging, but there are certainly sports related things we could do, lets get a few more ideas and then we can set up some sort of vote

**Comment by jacksonwalters** [comment]
The 2018 midterm elections are coming up. Could be interesting to try and forecast outcomes in congress.

**Comment by ZachGlassman** [comment]
Also a very interesting issue.  Just a note, this model is really tuned for timeseries data that has periodicities and other things like that.

**Comment by sdorsher** [comment]
When you say that, my first thought is power grid usage, outages, and fluctuations. But I don't think we can get access to that information. More reasonably, stock market data, though I personally seem to be having a hard time accessing that. Twitter is technically a time series, though forecasting twitter data is non-obvious. I would have said something more specific like forecasting fuel prices, but I am not sure that data is public either. We could _actually go back to pure science_ and forecast the next gravitational wave detection, though the data is a little sparse. Probably this is possible but it's sort of like insider trading for me-- definitely scummy.

**Comment by craw-daddy** [comment]
I'd have to check around for data sources, but how about not predicting the stock market (as there's so many variables that could be considered), but predicting something slightly more mundane like (wholesale) milk prices or the price of some good(s).  Or if not prices, then milk production quantities (or similar).  Or something more off the wall like BSE incidents in cattle.  (I don't know if those are particularly seasonal, but maybe they are because of births, etc.)

**Comment by ZachGlassman** [comment]
Remember you will not be creating the model (this is already done) rather you will be interacting with it through an API.  The goal here is to create the infrastructure to use the model as a service in a larger application.  We can tune the model once we have the rest of the code written.

**Comment by sdorsher** [comment]
Forcasting data relies on past trends. I suggest making use of Fourier structure of the data. This is not reinventing any specific past project of mine, rather, pretty much all of them.

**Comment by sdorsher** [comment]
The purpose was to test github collaboration and see if we could learn to work together and learn the interface. Failure. Issue closed.
